### ISSUE TITLE
Missing QBoy/Core/Rom.hpp

### ISSUE THREAD

**Issue by yenatch** [Diegoisawesome/AwesomeMapEditor#4]
When I try to build:

```
C:\AwesomeMapEditor\include\AME\Forms\MainWindow.h:42: error: QBoy/Core/Rom.hpp: No such file or directory
```

**Comment by Sierraffinity** [comment]
Do you have [QBoy](https://github.com/pokedude9/QBoy) in the root of your C drive as well? If so, you may have to change your build directory to just `bin` instead of the long name it gives you, for both QBoy and AME.

**Comment by FredrIQ** [comment]
I got the same issue as yenatch (but not on Windows) and went here.
I got on hold of QBoy (which, by the way, is not listed as a dependency anywhere unless I'm blind) and copied it where it seemed to want it. After doing this, the make process went a bit further, but it seems to rely on the file system being case insensitive.

```
In file included from include/AME/System/LoadedData.hpp:47:0,
                 from src/Forms/MainWindow.cpp:34:
include/AME/Graphics/OverworldTable.hpp:42:35: ödesdigert fel: qboy/Graphics/Image.hpp: Filen eller katalogen finns inte
 #include <qboy/Graphics/Image.hpp>
                               ^
```

Compare with QBoy in other #includes.
I changed 2 offending case inconsistencies in the mentioned file by hand, and now got stuck on this

```
src/System/Configuration.cpp:40:27: ödesdigert fel: yaml-cpp/yaml.h: Filen eller katalogen finns inte
 #include <yaml-cpp/yaml.h>
                           ^
```

...and now I'm not sure if I want to bother. Will there be more surprises, or are dependecies listed somwehere?

(Translations: ödesdigert fel -> fatal error, Filen eller katalogen finns inte -> No such file or directory)

**Comment by FredrIQ** [comment]
OK, I went ahead anyway and got on hold of yaml-cpp, turns out it was the only other dependecy. The result compiled, but it would be nice if the README documented dependecies or similar.

**Comment by Sierraffinity** [comment]
Sorry man, it should have been clearer. Hopefully the new additions in the latest commit make it easier for people to get started building this.
