### ISSUE TITLE
Missing configuration files

### ISSUE THREAD

**Issue by FredrIQ** [Diegoisawesome/AwesomeMapEditor#5]
There are missing (default) configuration files. After creating this by hand -- http://sprunge.us/OdBR -- the editor loaded. After attempting to load a ROM, the editor crashed with similar issues, seemingly because of a missing game-specific (or possibly header-specific, haven't investigated) config. It would be nice if the editor fell back to reasonable defaults to the former, and perhaps throw an error or load defaults based on ROM header for the latter.

**Comment by pokedude9** [comment]
Hey FredrIQ,

we will be doing a guide with build instructions soon. In the meanwhile, fix that issue by copying the "resources/config" directory to the directory in which the executable is located in. This ensures that at least BPRE will load correctly.

Best regards,
Pokedude
