### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by hugmanrique** [Diegoisawesome/AwesomeMapEditor#8]
I have being trying for 3+ hours, but no success 😢 

My file structure is as follows

AwesomeMapEditor
../QBoy
..../bin
../yaml-cpp
..../bin
/bin

I configured all the 3 projects to compile to children /bin directories as shown above. I added QBoy and yaml-cpp as dependencies to the AwesomeMapEditor project, I even went to the ``AwesomeMapEditor.pro`` file and changed:

```cpp
INCLUDEPATH += $$PWD/../QBoy/include
DEPENDPATH  += $$PWD/../QBoy/include
INCLUDEPATH += $$PWD/../yaml-cpp/include
DEPENDPATH += $$PWD/../yaml-cpp/include
QMAKE_LFLAGS += -static-libgcc -static-libstdc++
win32: LIBS += -lopengl32

CONFIG(debug, debug|release) {
    unix|win32: LIBS += -L$$PWD/../QBoy/bin/debug/ -lQBoy
    unix|win32: LIBS += -L$$PWD/../yaml-cpp/bin/debug/ -lyaml-cpp
} else {
    unix|win32: LIBS += -L$$PWD/../QBoy/bin/release/ -lQBoy
    unix|win32: LIBS += -L$$PWD/../yaml-cpp/bin/release/ -lyaml-cpp
}
```
by

```cpp
INCLUDEPATH += $$PWD/QBoy/include
DEPENDPATH  += $$PWD/QBoy/include
INCLUDEPATH += $$PWD/yaml-cpp/include
DEPENDPATH += $$PWD/yaml-cpp/include
QMAKE_LFLAGS += -static-libgcc -static-libstdc++
win32: LIBS += -lopengl32

CONFIG(debug, debug|release) {
    unix|win32: LIBS += -L$$PWD/QBoy/bin/debug/ -lQBoy
    unix|win32: LIBS += -L$$PWD/yaml-cpp/bin/debug/ -lyaml-cpp
} else {
    unix|win32: LIBS += -L$$PWD/QBoy/bin/release/ -lQBoy
    unix|win32: LIBS += -L$$PWD/yaml-cpp/bin/release/ -lyaml-cpp
}
```

Please note that I don't have any experience with C++ and it is my first time using Qt. Do you see something I'm missing? These are the errors I'm getting:

![](http://i.hugmanrique.me/PXhP1g.png)

There are other 40 errors, but it doesn't seem like it's the fault of the project. I think they Yaml-cpp library is missing, but I don't know what to change to make it work

**Comment by Sierraffinity** [comment]
You need to structure it more like this:

- AwesomeMapEditor
  - /bin
- QBoy
  - /bin
- yaml-cpp
  - /bin

Then pop the .pro provided in the `deps` folder into the yaml-cpp folder, open all the projects in the editor, and build them.

**Comment by hugmanrique** [comment]
I've changed the file structure as you told me, moved the yaml-cpp.pro file to the yaml-cpp folder but it still fails:

![Some errors it throws](http://i.hugmanrique.me/ljoSfl.png)

I added the two projects as dependencies and their building paths are /bin (they are created) but it throws these crap ton of errors while building AME

**Comment by hugmanrique** [comment]
I can't still figure out what the problem is 😞. I'm sorry if it's something trivial, but I would like to try this editor

**Comment by Sierraffinity** [comment]
I'm puzzled myself. Did you revert your changes to the pro file? And how did you get yaml-cpp when you downloaded it? You'll want to use the version up on GitHub instead of a 'release' because the release version uses Boost which acts weirdly when we use it in our project.

**Comment by hugmanrique** [comment]
I reverted the .pro files by git cloning the project and the dependencies. I cloned the last master commit of yaml-cpp. Should I test with an specific branch or commit?

**Comment by Sierraffinity** [comment]
We're using [this commit](https://github.com/jbeder/yaml-cpp/commit/519d33fea3fbcbe7e1f89f97ee0fa539cec33eb7), you might want to try with that. Have you tried cleaning everything and running qmake on yaml-cpp? If this doesn't fix it I might just resort to helping you out personally over TeamViewer if you would like.

**Comment by hugmanrique** [comment]
I fetched that commit and resetted the git internal repo and I still receive 84 issues (all of them are related with yaml-cpp). I would prefer not to give someone access to my PC through TeamViewer, but I would share my screen through Skype.

More details:
- Using Win 10.1
- Compiling with Desktop Qt 5.7.1 MinGW 32bit
- AME has yaml-cpp and QBoy as dependencies ![](http://i.hugmanrique.me/YrFMQC.png)
- QBoy has yaml-cpp as a dependency ![](http://i.hugmanrique.me/Wo8ti6.png)
- I copied the yaml-cpp.pro file into the yaml-cpp folder
- Folder structure:
  - QBoy
    - bin
  - AwesomeMapEditor
    - bin
  - yaml-cpp
    - bin
- Compiled all the projects in debug mode
- Some of the errors I'm getting ![ton heck of errors](http://i.hugmanrique.me/4fmPBv.png)

**Comment by hugmanrique** [comment]
@Diegoisawesome helped me for over 30 mins with this issue I had and it finally worked!
